CREATE TABLE [security].[User](
  [Id] INT NOT NULL PRIMARY KEY IDENTITY, 
  [UniqueId] UNIQUEIDENTIFIER NOT NULL DEFAULT newid(), 
  [Login] NVARCHAR(100) NOT NULL, 
  [Password] NVARCHAR(1000) NOT NULL, 
  [Salt] NVARCHAR(1000) NOT NULL, 
  [FirstName] NVARCHAR(50) NOT NULL, 
  [LastName] NVARCHAR(50) NOT NULL, 
  [LastNamePrefix] NVARCHAR(50) NULL
) ON [PRIMARY];
